# Generated by Django 3.0.2 on 2020-03-06 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('nationality', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('player1', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_player', to='game.Player')),
                ('player10', models.ForeignKey(blank=True, default=90, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player10_player', to='game.Player')),
                ('player2', models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_player', to='game.Player')),
                ('player3', models.ForeignKey(blank=True, default=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_player', to='game.Player')),
                ('player4', models.ForeignKey(blank=True, default=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_player', to='game.Player')),
                ('player5', models.ForeignKey(blank=True, default=40, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player5_player', to='game.Player')),
                ('player6', models.ForeignKey(blank=True, default=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player6_player', to='game.Player')),
                ('player7', models.ForeignKey(blank=True, default=60, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player7_player', to='game.Player')),
                ('player8', models.ForeignKey(blank=True, default=70, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player8_player', to='game.Player')),
                ('player9', models.ForeignKey(blank=True, default=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player9_player', to='game.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('atp_points', models.IntegerField()),
                ('player', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.Player')),
            ],
        ),
    ]
