# Generated by Django 3.0.2 on 2020-03-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player1',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player10',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player10_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player2',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player3',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player4',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player5',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player5_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player6',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player6_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player7',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player7_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player8',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player8_player', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player9',
            field=models.ForeignKey(blank=True, default=502, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player9_player', to='game.Player'),
        ),
    ]
