# Generated by Django 3.0.2 on 2020-02-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player10',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player6',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player7',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player8',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player9',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
