# Generated by Django 3.0.2 on 2020-01-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200130_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_tournament',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team_tournament',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='user_tournament',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='user_tournament',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Tournament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team_Player',
        ),
        migrations.DeleteModel(
            name='Team_Tournament',
        ),
        migrations.DeleteModel(
            name='User_Tournament',
        ),
    ]
