# Generated by Django 3.0.2 on 2020-02-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200130_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
