# Generated by Django 3.0.2 on 2020-03-22 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200311_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='date_created',
        ),
        migrations.AddField(
            model_name='player',
            name='date_created_player',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerscore',
            name='date_created_playerScore',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
        migrations.AddField(
            model_name='team',
            name='date_created_team',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date_created_tournament',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
    ]
