# Generated by Django 3.0.2 on 2020-02-18 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200205_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
    ]
