# Generated by Django 3.0.2 on 2020-03-26 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200322_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_created_player',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created_player'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='date_created_playerScore',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created_playerScore'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created_team',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created_team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_created_tournament',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created_tournament'),
        ),
    ]
