# Generated by Django 2.1.15 on 2020-04-03 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200326_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScoreDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('date_created_playerScoreDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created_playerScore')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='week',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='year',
        ),
        migrations.AddField(
            model_name='playerscore',
            name='playerScoreDate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.PlayerScoreDate'),
        ),
    ]
