# Generated by Django 2.1.15 on 2020-04-03 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200403_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscoredate',
            name='date_created_playerScoreDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date_created_playerScore'),
        ),
    ]
