# Generated by Django 2.1.15 on 2020-04-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200403_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscore',
            name='date_created_playerScore',
        ),
    ]
