# Generated by Django 2.1.15 on 2020-04-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200405_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='playerScoreDate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.PlayerScoreDate', verbose_name='Date'),
        ),
    ]
